baseURL = "https://taichinhdongian.netlify.app"
languageCode = "vi"
#title = "Tài chính đơn giản"
theme = "prav"

[taxonomies]
   tag = "tags"
   category = "categories"
   
[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404

pygmentsCodeFences = "true"
pygmentsStyle = "perldoc"
pagination = "true"

#googleanalytics = ""
#disqusShortname = ""

# Below settings are used throughout the theme. Please update
[params]
  title = "Tài chính đơn giản"
  tagline = "Đến hòn đá cũng hiểu"
  author = "Long Vũ"
  body_classes = "avenir bg-near-white"

[social]
  email = "mailto:vuduclong2005@gmail.com"
  facebook = "https://www.facebook.com/long.vuduc"
  twitter = "http://twitter.com/tudomuonnam"
  #medium = "https://www.medium.com/@pravin"
  #github = "https://github.com/pravin"
  #linkedin = "http://uk.linkedin.com/in/pravinp"


# Set unsafe mode to allow markdownify to work with goldmark
# This is important. Please do not delete. It is used to re-render markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true